modified OD class,1st review
CarolLu85/Git_Practice pull request #4
Opened 2024-04-09 06:29 UTC by JasmineJ11

2024-04-09 06:52 UTC, CarolLu85 requested changes
pls delete unrelevant comments

2024-04-09 19:19 UTC, wxxty12 requested changes
needs some improvements

2024-04-10 10:39 UTC, CarolLu85 approved these changes

2024-04-10 10:44 UTC, wxxty12 approved these changes

2024-04-10 10:48 UTC, merged